name: data-excavator
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - jupyterlab
  - ipython
  - notebook
  - flask
  - dask
  - python-dotenv
  - pyyaml
  - git-lfs
